version: "1.0"
services:
  db:
    image: postgres:latest
    container_name: db-higher-lower
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - db-higher-lower:/var/lib/postgresql/data
    ports:
      - 5432:5432

  api:
    build:
      context: .
    container_name: api-higher-lower
    env_file:
      - ".env"
    ports:
      - "${PORT}:${PORT}"
    environment:
      - WAIT_HOSTS=${DATABASE_HOST}:${POSTGRES_PORT}
      - WAIT_SLEEP_INTERVAL=3
    depends_on:
      - db

volumes:
  db-higher-lower:
