version: "1.0"
services:
  db:
    image: postgres:latest
    container_name: db-higher-lower
    env_file:
      - "./.env"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - db-higher-lower:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db-higher-lower:
